"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[package]
disabled = true

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[time]
disabled = false
format = '[$time]($style) '
time_format = '%Y-%m-%d %T'
utc_time_offset = '+1'

[c]
detect_extensions = [ "c", "h", "cpp", "hpp", "cxx", "hxx" ]
