# ENVIRONMENT VARIABLES
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,
#env = ELECTRON_OZONE_PLATFORM_HINT, auto

env = NVD_BACKEND, direct
env = GTK_THEME, 

# Hyprland Environment Variables
env = HYPRLAND_TRACE, 1
env = HYPRLAND_NO_RT, 1
env = HYPRLAND_NO_SD_NOTIFY, 1
env = HYPRLAND_NO_SD_VARS, 1
env = HYPRCURSOR_SIZE,24

# XDG Specifications
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland

# Toolkit Backend Variables
env = GDK_BACKEND, wayland,x11,*
env = SDL_VIDEODRIVER, wayland
env = CLUTTER_BACKEND, wayland

# Qt Variables
env = QT_QPA_PLATFORM, wayland;xcb
env = QT_QPA_PLATFORMTHEME, qt6ct
env = QT_AUTO_SCREEN_SCALE_FACTOR, 1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION, 1

# Nvidia Specific
env = GBM_BACKEND, nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME, nvidia
env = LIBVA_DRIVER_NAME, nvidia
