splash = false
ipc = on

wallpaper {
    monitor =
    path = ~/$XDG_PICTURES_DIR/wallpapers/outer-wilds.jpg
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/$XDG_PICTURES_DIR/wallpapers/outer-wilds.jpg
    fit_mode = cover
}
